# Generated by Django 3.1 on 2021-07-22 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_page', '0001_initial'),
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catalog',
            options={'default_related_name': 'Catalog', 'ordering': ('-created_at',), 'verbose_name': 'Catalog', 'verbose_name_plural': 'Catalog'},
        ),
        migrations.RemoveField(
            model_name='catalog',
            name='id',
        ),
        migrations.RemoveField(
            model_name='catalog',
            name='title',
        ),
        migrations.AddField(
            model_name='catalog',
            name='basepage_ptr',
            field=models.OneToOneField(auto_created=True, default=11, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='Catalog', serialize=False, to='garpix_page.basepage'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='catalog',
            name='content',
            field=models.TextField(blank=True, default='', verbose_name='Catalog'),
        ),
    ]
