# Generated by Django 3.1 on 2021-07-22 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_menu', '0002_auto_20210720_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='menu_type',
            field=models.CharField(choices=[('header_menu', 'Header menu'), ('footer_menu', 'Footer menu'), ('index_menu', 'Index menu')], default='', max_length=100, verbose_name='Тип меню'),
        ),
    ]
