# Generated by Django 3.1 on 2021-07-21 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('garpix_page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('basepage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='Content_category', serialize=False, to='garpix_page.basepage')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ('-created_at',),
                'default_related_name': 'Content_category',
            },
            bases=('garpix_page.basepage',),
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('basepage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='Content_page', serialize=False, to='garpix_page.basepage')),
                ('content', models.TextField(blank=True, default='', verbose_name='Content')),
                ('content_ru', models.TextField(blank=True, default='', null=True, verbose_name='Content')),
            ],
            options={
                'verbose_name': 'Page',
                'verbose_name_plural': 'Pages',
                'ordering': ('-created_at',),
                'default_related_name': 'Content_page',
            },
            bases=('garpix_page.basepage',),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('basepage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='Content_post', serialize=False, to='garpix_page.basepage')),
                ('content', models.TextField(blank=True, default='', verbose_name='Content')),
                ('content_ru', models.TextField(blank=True, default='', null=True, verbose_name='Content')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'ordering': ('-created_at',),
                'default_related_name': 'Content_post',
            },
            bases=('garpix_page.basepage',),
        ),
    ]
