# Generated by Django 3.1 on 2021-07-22 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_page', '0001_initial'),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Huy',
            fields=[
                ('basepage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='huy_page', serialize=False, to='garpix_page.basepage')),
                ('content', models.TextField(blank=True, default='', verbose_name='Hyuuuu')),
                ('content_ru', models.TextField(blank=True, default='', null=True, verbose_name='Hyuuuu')),
            ],
            options={
                'verbose_name': 'Huy',
                'verbose_name_plural': 'huys',
                'ordering': ('-created_at',),
                'default_related_name': 'huy_page',
            },
            bases=('garpix_page.basepage',),
        ),
    ]
